version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=OnlineShop.settings
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 OnlineShop.wsgi:application"

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=onlineshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@bb@s1366
