# Generated by Django 4.2.2 on 2023-07-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_image_productimage_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('product_id',), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
