# Generated by Django 4.2.2 on 2023-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_category_product_category_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product.category'),
        ),
    ]
