# Generated by Django 4.2.2 on 2023-08-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('user',), 'verbose_name': 'address', 'verbose_name_plural': 'address'},
        ),
    ]
