# Generated by Django 4.2.2 on 2023-08-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='main_address',
            field=models.BooleanField(default=False),
        ),
    ]
