# Generated by Django 4.2.2 on 2023-08-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expire_day',
            field=models.SmallIntegerField(default=30),
        ),
    ]
