# Generated by Django 4.2.2 on 2023-07-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('order_date',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ('order',), 'verbose_name': 'order item', 'verbose_name_plural': 'order items'},
        ),
    ]
