# Generated by Django 4.2.2 on 2023-08-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_number'),
        ('order', '0003_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
            preserve_default=False,
        ),
    ]
